Implementing multiversion docs
ansys/pymapdl-reader pull request #277
Opened 2023-06-29 14:28 UTC by clatapie

Closes #276.

2023-06-29 14:38 UTC, RobPasMue commented on .pre-commit-config.yaml
> -
Keep this hook @clatapie

2023-06-29 14:42 UTC, RobPasMue requested changes

2023-06-29 14:42 UTC, RobPasMue commented on doc/source/conf.py
As well as edit page buttons. Please add it

2023-06-29 14:42 UTC, clatapie commented on ansys/mapdl/reader/__init__.py
> -from . import _archive
It was not used by the file

2023-06-29 14:43 UTC, RobPasMue commented
Also, @clatapie - implementing Vale might be a burden really... let's just remove it from the workflow

2023-06-29 14:43 UTC, RobPasMue commented
> Also, @clatapie - implementing Vale might be a burden really... let's just remove it from the workflow

It wasn't present before either

2023-06-29 15:11 UTC, RobPasMue commented
Also... you removed the ``code-style``. That one should still be run. The one that you should remove is the ``doc-style`` stage.

2023-06-30 06:13 UTC, RobPasMue commented
I'm not sure it's a good idea removing the current ``setup.py``: it was doing a lot of different things for compilation of CPython modules + it's not really needed to switch to multiversion docs. Let's try to stay within the scope of the PR. Our GitHub actions work as well with a requirements folder containing requirements_*.txt files.

2023-06-30 15:17 UTC, RobPasMue commented
Closing in favor of #278

2023-06-30 15:17 UTC, closed without merging