fix: allow for numpy 1.X backwards compatibility
ansys/pymapdl-reader pull request #477
Opened 2024-08-19 10:07 UTC by RobPasMue

As title says. Allowing compatibility with both NumPy major versions (for now)

2024-08-19 10:50 UTC, RobPasMue commented on pyproject.toml
> +    "numpy>=1,<3",
```suggestion
    "numpy>=1.16.0,<3",
```

2024-08-19 17:52 UTC, germa89 requested changes

2024-08-19 20:53 UTC, akaszynski commented on ansys/mapdl/reader/cython/_binary_reader.pyx
> +        ndarray = np.array(array_wrapper, copy=False)
`copy=False` is indeed for performance reasons on numpy 1.X. Looking at the docs now, seems like the ideal approach would be `copy=None` for 2.X, as it copies only when necessary.

2024-08-20 07:43 UTC, RobPasMue commented on ansys/mapdl/reader/cython/_binary_reader.pyx
> +        ndarray = np.array(array_wrapper, copy=False)
Sure, I can change that.

2024-08-20 07:43 UTC, RobPasMue commented on ansys/mapdl/reader/cython/_binary_reader.pyx
> +        ndarray = np.array(array_wrapper)
```suggestion
        ndarray = np.array(array_wrapper, copy=None)
```

2024-08-20 07:44 UTC, RobPasMue commented
@germa89 - comments solved. Review and approve.

2024-08-20 15:26 UTC, akaszynski approved these changes
LGTM.

2024-08-20 16:43 UTC, germa89 approved these changes
Looks good to me. Thank you @RobPasMue and @akaszynski :)

2024-08-20 17:10 UTC, merged

2024-08-21 07:36 UTC, RobPasMue commented
Let me get the release done now, 0.54